services:
  web:
    build: .
    container_name: notes_backend
    env_file: 
    - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - notes_network

  mongodb:
    image: mongo:6.0
    container_name: notes_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - notes_network

networks:
  notes_network:

volumes:
  mongo_data:
